/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("forge.java-conventions")
}

dependencies {
    api(libs.com.badlogicgames.gdx.gdx)
    api(libs.com.badlogicgames.gdx.gdx.platform)
    api(libs.com.badlogicgames.gdx.gdx.freetype)
    api(libs.com.badlogicgames.gdx.gdx.backend.lwjgl)
    api(libs.com.badlogicgames.gdx.gdx.tools)
    api(libs.com.badlogicgames.gdx.gdx.freetype.platform)
    api(project(":forge-core"))
    api(project(":forge-gui"))
    api(project(":forge-gui-mobile"))
    api(libs.org.jetbrains.annotations)
    api(libs.com.badlogicgames.gdx.controllers.gdx.controllers.desktop)
}

description = "Forge Adventure"
