/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "forge"
include(":forge-ai")
include(":forge-gui")
include(":forge-game")
include(":forge-gui-desktop")
include(":forge-core")
//include(":forge-gui-mobile")
//include(":forge-gui-ios")
//include(":forge-gui-mobile-dev")
//include(":forge-adventure")
//include(":forge-gui-android")
//include(":forge-lda")
