/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("forge.java-conventions")
}

dependencies {
    api(project(":forge-core"))
    api(libs.com.googlecode.minlog)
    api(libs.io.sentry.sentry.logback)
    testImplementation(libs.org.testng.testng)
}

description = "Forge Game"

tasks.named<Test>("test") {
    useTestNG()
}
