/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("forge.java-conventions")
}

dependencies {
    api(libs.org.apache.httpcomponents.httpclient)
    api(libs.commons.codec.commons.codec)
    api(project(":forge-core"))
    api(project(":forge-game"))
    api(project(":forge-ai"))
    api(project(":forge-gui"))
    api(project(":forge-gui-mobile"))
    api(libs.io.sentry.sentry.android)
    api(libs.io.sentry.sentry.android.core)
    api(libs.io.sentry.sentry.android.ndk)
    api(libs.com.badlogicgames.gdx.controllers.gdx.controllers.android)
    compileOnly(libs.org.robolectric.android.all)
    compileOnly(libs.xmlpull.xmlpull)
    system(libs.de.cketti.fileprovider.public.fileprovider)
    system(libs.com.getkeepsafe.relinker.relinker)
    system(libs.com.badlogicgames.gdx.gdx.backend.android)
}

description = "Forge Android"
