/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("forge.java-conventions")
}

dependencies {
    api(project(":forge-core"))
    api(project(":forge-game"))
    api(project(":forge-ai"))
    api(libs.com.thoughtworks.xstream.xstream)
    api(libs.io.netty.netty.all)
    api(libs.org.fourthline.cling.cling.support)
    api(libs.org.lz4.lz4.java)
}

description = "Forge Gui"
