/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("forge.java-conventions")
}

dependencies {
    api(project(":forge-core"))
    api(project(":forge-game"))
    api(project(":forge-ai"))
    api(project(":forge-gui"))
    api(libs.org.apache.commons.commons.lang3)
    api(project(":forge-gui-desktop"))
}

description = "Forge LDA"
