/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("forge.java-conventions")
}

dependencies {
    api(project(":forge-core"))
    api(project(":forge-game"))
    api(project(":forge-ai"))
    api(project(":forge-gui"))
    api(libs.com.github.tommyettinger.textratypist)
    api(libs.com.badlogicgames.gdx.controllers.gdx.controllers.core)
    api(libs.com.badlogicgames.gdx.gdx)
    api(libs.com.badlogicgames.gdx.gdx.freetype)
    api(libs.com.github.raeleus.tenpatch.tenpatch)
    api(libs.com.badlogicgames.gdx.gdx.box2d)
    api(libs.com.badlogicgames.gdx.gdx.ai)
}

description = "Forge Mobile"
