/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("forge.java-conventions")
}

dependencies {
    api(project(":forge-core"))
    api(project(":forge-game"))
    api(project(":forge-ai"))
    api(project(":forge-gui"))
    api(project(":forge-gui-mobile"))
    api(libs.com.badlogicgames.gdx.gdx.backend.robovm)
}

description = "Forge iOS"
