/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("forge.java-conventions")
}

dependencies {
    api(libs.com.google.guava.guava)
    api(libs.org.apache.commons.commons.lang3.x1)
}

description = "Forge Core"
