/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("forge.java-conventions")
}

dependencies {
    api(project(":forge-gui-mobile"))
    api(libs.com.badlogicgames.gdx.gdx.backend.lwjgl3)
    api(libs.com.badlogicgames.gdx.gdx.platform)
    api(libs.com.badlogicgames.gdx.gdx.freetype.platform)
    api(libs.commons.cli.commons.cli)
    api(libs.com.badlogicgames.gdx.controllers.gdx.controllers.desktop)
    api(libs.com.badlogicgames.gdx.gdx.box2d.platform)
}

description = "Forge Mobile Dev"
